package com.example.memes_for_everything;

public class AllMemesList {

    public static MemeSound[] All = new MemeSound[] {
            new MemeSound("Уточка","?", "Настроение", R.raw.a1, R.drawable.a1),
            new MemeSound("Грусть","?", "Настроение", R.raw.a2, R.drawable.a2),
            new MemeSound("Шизофрения","Гоблин", "Фраза", R.raw.a3, R.drawable.a3),
            new MemeSound("Этого казино","?", "Фраза", R.raw.a4, R.drawable.a4),
            new MemeSound("Nigger","oldspice", "Настроение", R.raw.a5, R.drawable.a5),
            new MemeSound("Телефон","?", "Настроение", R.raw.a6, R.drawable.a6),
            new MemeSound("СЛАВЯНСКИЙ ЗАЖИМ ЯЙЦАМИ","Русь", "Русы и ящеры", R.raw.a7, R.drawable.a7),
            new MemeSound("Ох, зря я туда полез","КотБегемот", "Страшилки", R.raw.a8, R.drawable.a8),
            new MemeSound("Не надо было это кушать","КотБегемот", "Страшилки", R.raw.a9, R.drawable.a9),
            new MemeSound("Ура, я пидорас!","Дискорд", "Секс", R.raw.a10, R.drawable.a10),
            new MemeSound("Нюхай бэбру","Бебра", "Дело в шляпе", R.raw.a11, R.drawable.a11),
            new MemeSound("Kiss me again","Ютуб", "Анимешная тяночка, женщина", R.raw.a12, R.drawable.a12),
            new MemeSound("Братишка, я тебе покушать принёс","Зелёный слоник", "зеленый слоник, говно", R.raw.a13, R.drawable.a13),
            new MemeSound("Одна история охуительнее другой","Зелёный слоник", "зеленый слоник, говно", R.raw.a14, R.drawable.a14),
            new MemeSound("Обосрался пидорас","Зелёный слоник", "зеленый слоник, говно", R.raw.a15, R.drawable.a15),
            new MemeSound("Начальник блять!","Зелёный слоник", "зеленый слоник, говно", R.raw.a16, R.drawable.a16),
            new MemeSound("Чисти чисти","Зелёный слоник", "зеленый слоник, говно", R.raw.a17, R.drawable.a17),
            new MemeSound("С нами лесбиянка и пансексуал","Ютуб", "с нами лесбиянка, гей, гендеры, пидорасы", R.raw.a18, R.drawable.a18),

            new MemeSound("Я футбольный мячик","", "", R.raw.a19, R.drawable.a19),
            new MemeSound("Амогус","", "", R.raw.a20, R.drawable.a20),
            new MemeSound("Да ты чё... бляяя","", "", R.raw.a21, R.drawable.a21),
            new MemeSound("Ты что, дурак что-ли","", "", R.raw.a22, R.drawable.a22),
            new MemeSound("Это мой гриб","", "", R.raw.a23, R.drawable.a23),
            new MemeSound("Пончики","", "", R.raw.a24, R.drawable.a24),
            new MemeSound("Bruh","Брух", "", R.raw.a25, R.drawable.a25),
            new MemeSound("Чёрный сталкер","черный сталкер", "", R.raw.a26, R.drawable.a26),

            new MemeSound("Система поиска пидорасов","?", "Геи, прикол", R.raw.a27, R.drawable.a27),

            new MemeSound("Говно, залупа, пенис","Оксимирон", "маты", R.raw.a28, R.drawable.a28),
            new MemeSound("Ямете кудасай","Аниме", "", R.raw.a29, R.drawable.a29),
            new MemeSound("Не надо, дядя","Аниме", "", R.raw.a30, R.drawable.a30),
            new MemeSound("Не надо, дядя 2","Папич", "", R.raw.a31, R.drawable.a31),
            new MemeSound("Я ебу собак","Ебанько", "зоофил", R.raw.a32, R.drawable.a32),
            new MemeSound("Кто куда, а я...","по съёбам", "", R.raw.a33, R.drawable.a33),
            new MemeSound("Самый лучший метод лечения геморроя","Попов", "живой огурец", R.raw.a34, R.drawable.a34),
            new MemeSound("Пожарная тревога","ГРОМКО", "огнетушитель, огонь", R.raw.a35, R.drawable.a35),
            new MemeSound("Дирижабль, ага","Титор", "", R.raw.a36, R.drawable.a36),
            new MemeSound("Сер да сер","свофорд", "война, военкомат, армия", R.raw.a38, R.drawable.a38),
            new MemeSound("Расстрелять","Иосиф Сталин", "СССР, армия", R.raw.a39, R.drawable.a39),
            new MemeSound("Немецкий марш","nazi are bad!", "германия", R.raw.a40, R.drawable.a40),
            new MemeSound("Was Wollen trinken","nazi are bad!", "германия", R.raw.a41, R.drawable.a41),
            new MemeSound("Гойда","Хз, кто это", "Россия", R.raw.a42, R.drawable.a42),
            new MemeSound("Аллах Акбар","Ислам", "Террористы, терроризм", R.raw.a43, R.drawable.a43),
            new MemeSound("Мортал комбат","Музыка", "", R.raw.a44, R.drawable.a44),
            new MemeSound("Женщина?! Жееенщина!","HOI4", "хойка, женщины", R.raw.a47, R.drawable.a47),
            new MemeSound("ВММЖТПОПРИКБ","Хортон видит ктошек", "в моём мире живут только пони", R.raw.a49, R.drawable.a49),
            new MemeSound("ЯЛКВМОМ","Ютуб", "Я люблю, когда волосатые мужики", R.raw.a50, R.drawable.a50),
            new MemeSound("2 пакетика травы","Ютуб", "наркотики зло", R.raw.a52, R.drawable.a52),
            new MemeSound("К Элизе","Классическая музыка", "классика", R.raw.a81, R.drawable.a81),
            new MemeSound("Совсем неожиданное заявление","Доктор Ливси", "сейчас мы будем заниматься сексом", R.raw.a83, R.drawable.a83),
            new MemeSound("Это классика, это знать надо","Зелёный слоник", "зеленый слоник", R.raw.a150, R.drawable.a150),
            new MemeSound("А я знаю, что ты др...","Ютуб", "секс, дрочешь, недрочабрь", R.raw.a152, R.drawable.a152),
            new MemeSound("UwW","Ня", "аниме, няшки, милашка, фембои, женщины, девушки, секс", R.raw.a155, R.drawable.a155),

    };
}
